AllCops:
  TargetRubyVersion: 2.4

# Rails:
#   Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# Layout/IndentationConsistency:
#   AllowProtectedAndPrivateMethodsBeIndented: true

# Rails/RelativeDateConstant:
#   Enabled: false

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
