AllCops:
  TargetRubyVersion: 2.4

  # RunRailsCops: true

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IndentationConsistency:
  AllowProtectedAndPrivateMethodsBeIndented: true
